### PR TITLE
remove Layer2Info monitoring template

### PR DESCRIPTION
**Pull request by ssbunyk**

### CODE REVIEW

**Comment by byshovets** [comment]
Do we need to create migrate for such changes?

**Comment by ssvsergeyev** [comment]
May be Vadim has a point?

**Comment by ssbunyk** [comment]
From Edd: On 1.0.3 release, the Layer2Info template exist but was not binded to a device class. On 1.1.0dev, the ZP now collects client mac address using the ClientMACs plugin so it no longer needs the Layer2Info template to be binded. 

So, it is possible, but why?

**Comment by byshovets** [comment]
Because we might need to consider possible situation when someone has already bound this template.

**Pull request merged**
